export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const SELECT_CITY = 'SELECT_CITY';
export const DESELECT_CITY = 'DESELECT_CITY';
export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const SUCCESS_WEATHER = 'SUCCESS_WEATHER';
